package com.pluto.plugin.utilities.sharing

import androidx.activity.ComponentActivity
import androidx.activity.viewModels
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels

fun Fragment.lazyContentSharer(): Lazy<ContentShareViewModel> = activityViewModels()

fun ComponentActivity.lazyContentSharer(): Lazy<ContentShareViewModel> = viewModels()

data class Shareable(
    val title: String,
    val content: String,
    val fileName: String = "File shared from Pluto"
) {
    val processedContent: String = StringBuilder().apply {
        append(content)
        append("\n\n-------------------------------------\nreport generated by Pluto (https://plutolib.com)")
    }.toString()
}

sealed class ShareAction {
    data class ShareAsText(val shareable: Shareable) : ShareAction()
    data class ShareAsFile(val shareable: Shareable, val type: String = "text/*") : ShareAction()
    data class ShareAsCopy(val shareable: Shareable) : ShareAction()
}
