plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}
apply from: "$rootDir/scripts/pluginBuilder.gradle"

ext {
    PUBLISH_GROUP_ID = "com.plutolib"
    PUBLISH_ARTIFACT_ID = 'plugin'
}

android {
    resourcePrefix 'pluto___'
    namespace 'com.pluto.plugin'
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)

    api(libs.androidx.constraintlayout)
    api(libs.androidx.navigation.fragment)
    api(libs.androidx.recyclerview)

    api(libs.google.material)

    api(libs.androidx.cardview)

    api(libs.androidx.lifecycle.common)
    api(libs.androidx.lifecycle.runtime)
}