## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Thu Sep 14 17:27:07 IST 2023
android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"

# Maven Central publish credentials
mavenCentralUsername=XXXX
mavenCentralPassword=XXXX
signing.keyId=XXXX
signing.password=XXXX
signing.secretKeyRingFile=XXXX

# Maven Central publish pom details
pom.inceptionYear=2024
pom.url=https://androidpluto.com
pom.license.name=The Apache Software License, Version 2.0
pom.license.url=http://www.apache.org/licenses/LICENSE-2.0.txt
pom.developer.id=srtvprateek
pom.developer.name=Prateek Srivastava
pom.developer.email=srtv.prateek@gmail.com
pom.scm.connection=https://github.com/androidPluto/pluto
pom.scm.developerConnection=https://github.com/srtvprateek
pom.scm.url=https://github.com/androidPluto/pluto

