plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}
apply from: "$rootDir/scripts/pluginBuilder.gradle"

ext {
    PUBLISH_GROUP_ID = "com.plutolib.plugins"
    PUBLISH_ARTIFACT_ID = 'network-no-op'
}

android {
    namespace 'com.pluto.plugins.network'
}

dependencies {
}