apply plugin: 'maven-publish'
apply plugin: 'signing'

apply from: "$rootDir/scripts/publish/_dokkaUtils.gradle"
apply from: "$rootDir/scripts/publish/_pomConfig.gradle"

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId PUBLISH_GROUP_ID
                artifactId PUBLISH_ARTIFACT_ID
                version PUBLISH_VERSION
                from components.release

                artifact androidSourcesJar
                artifact javadocJar

                configurePom(pom, PUBLISH_ARTIFACT_ID)
            }
        }
    }
}

signing {
    useInMemoryPgpKeys(
            rootProject.ext["signing.keyId"],
            rootProject.ext["signing.key"],
            rootProject.ext["signing.password"]
    )
    sign publishing.publications
}
