plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}
apply from: "$rootDir/scripts/pluginBuilder.gradle"

ext {
    PUBLISH_GROUP_ID = "com.plutolib.plugins"
    PUBLISH_ARTIFACT_ID = 'bundle-core-no-op'
}

android {
    namespace 'com.pluto.plugins.bundle.core'
}

dependencies {
    api project(path: ':pluto-plugins:plugins:exceptions:lib-no-op')
    api project(path: ':pluto-plugins:plugins:network:core:lib-no-op')
    api project(path: ':pluto-plugins:plugins:network:interceptor-okhttp:lib-no-op')
    api project(path: ':pluto-plugins:plugins:network:interceptor-ktor:lib-no-op')
    api project(path: ':pluto-plugins:plugins:shared-preferences:lib-no-op')
    api project(path: ':pluto-plugins:plugins:logger:lib-no-op')
    api project(path: ':pluto-plugins:plugins:datastore:lib-no-op')
    api project(path: ':pluto-plugins:plugins:rooms-database:lib-no-op')
    api project(path: ':pluto-plugins:plugins:layout-inspector:lib-no-op')
}