plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}
apply from: "$rootDir/scripts/pluginBuilder.gradle"

ext {
    PUBLISH_GROUP_ID = "com.plutolib"
    PUBLISH_ARTIFACT_ID = 'pluto-no-op'
}

android {
    namespace 'com.pluto'
}

dependencies {
    implementation(libs.androidx.core)
}