plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
}
apply from: "$rootDir/scripts/pluginBuilder.gradle"

ext {
    PUBLISH_GROUP_ID = "com.plutolib.plugins"
    PUBLISH_ARTIFACT_ID = "network-interceptor-ktor"
}

android {
    resourcePrefix 'pluto_network___'
    namespace 'com.pluto.plugins.network.ktor'
}

dependencies {
//    implementation 'com.plutolib:plugin:2.0.0'
//    implementation project(':pluto-plugins:base:lib')
    implementation project(':pluto-plugins:plugins:network:core:lib')

    implementation(libs.ktor.client.core.jvm)
}