apply from: "$rootDir/scripts/version.gradle"
apply from: "$rootDir/scripts/publish/publish.gradle"


def version = loadVersioningData()
def verCode = version["code"]
def verPublish = version["publish"]
def verGitSHA = version["gitSha"]

ext {
    PUBLISH_VERSION = verPublish
}

android {
    compileSdk = libs.versions.compileSdk.get().toInteger()
    buildToolsVersion = libs.versions.buildTools.get()

    buildFeatures {
        viewBinding true
    }

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()

        buildConfigField ("String", "VERSION_NAME", "\"${verPublish}\"")
        buildConfigField ("long", "VERSION_CODE", "${verCode}")
        buildConfigField ("String", "GIT_SHA", "\"${verGitSHA}\"")
    }

    buildTypes {
        release {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
    }

    kotlinOptions {
        jvmTarget = libs.versions.java.get()
    }

    lint {
        abortOnError false
    }
}