package com.pluto.core

import androidx.core.content.FileProvider

/**
 * Custom FileProvider implementation for Pluto.
 *
 * This class extends Android's FileProvider to enable secure file sharing
 * between Pluto and other applications. It's used for sharing logs, screenshots,
 * and other files generated by Pluto's debugging tools.
 */
internal class PlutoFileProvider : FileProvider()
