name: CI

on:
#   push:
#     branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./gradlew --no-daemon --max-workers 8 --build-cache assembleDebug

  build-no-op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build No Op
        run: ./gradlew --no-daemon --max-workers 8 --build-cache assembleDebugNoOp

  ktlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validating Ktlint
      run: ./gradlew --no-daemon --max-workers 8 --build-cache ktlintCheck

  detekt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verifying detekt
      run: ./gradlew --no-daemon --max-workers 8 --build-cache detekt
