name: Daily Builds

on:
  schedule:
  - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./gradlew --no-daemon --max-workers 8 --build-cache build
